/* version.h - the VERSION, the build DATE and the git HASH, in ONE place.
 *
 * === WHY THIS HEADER EXISTS (S85, 2026-08-29) ===
 *
 * The version was HARDCODED in `main.cpp` ("v0.3.0") and, separately, in
 * `CMakeLists.txt` (`VERSION_MAJOR/MINOR/ALTER`, which numbers the shipped
 * package). Two places, no link between them: the first time we published a
 * 0.4.0, the log would have kept announcing 0.3.0 and nobody would have noticed
 * until they needed it. So the version comes from CMake, for everyone, and
 * nobody copies it.
 *
 * === WHY THREE MACROS AND NOT ONE STRING TO SPLIT ===
 *
 * S3 had carved a single string, `SHADOW_BUILD_ID` = "date Z hash". That is
 * enough for a log line but not for a screen: showing three pieces of
 * information on three lines would force us to RE-SPLIT at runtime what CMake
 * had just glued together - a `strrchr(' ')` that breaks the day the timestamp
 * format changes, and breaks SILENTLY (you read a truncated date, not an
 * error). So CMake emits the three atoms separately, and it is the COMPOSITION
 * that is derived, not the decomposition.
 *
 * `SHADOW_BUILD_ID` stays defined here, identical, because it is worth more than
 * a log line; it is simply recomposed from the atoms.
 *
 * === WHAT THIS HEADER COSTS ===
 *
 * `build_id.h` is REGENERATED on every compilation (that is the point of S3: a
 * hash that does not move lies, and we have twice tested a stale binary
 * believing otherwise). Everything that includes `version.h` therefore
 * recompiles on every `make`. We keep it to THREE files - the entry point, the
 * boot error screen, the "About" screen - and that is why it must not be
 * included from a widely-included header.
 *
 * The fallback values are NOT plausible lies: "inconnue" and "nogit" are visible
 * on screen. A credible fallback date would send someone looking for a binary
 * that does not exist.
 */
#ifndef SHADOW_VERSION_H
#define SHADOW_VERSION_H

/* Generated by CMake into the build directory (see CMakeLists.txt, target
 * `shadow_build_id`). Absent = a compilation outside our CMake: we keep
 * fallbacks rather than an error, so a plain trial `gcc` still goes through. */
#if defined(__has_include)
#  if __has_include("build_id.h")
#    include "build_id.h"
#  endif
#endif

#ifndef SHADOW_VERSION
#define SHADOW_VERSION "0.0.0"
#endif
#ifndef SHADOW_BUILD_DATE
#define SHADOW_BUILD_DATE "inconnue"
#endif
#ifndef SHADOW_BUILD_HASH
#define SHADOW_BUILD_HASH "nogit"
#endif

/* A single line, for the log and for the boot error screen: where there is only
 * room for one string, and where we want EVERYTHING. */
#ifndef SHADOW_BUILD_ID
#define SHADOW_BUILD_ID SHADOW_BUILD_DATE " " SHADOW_BUILD_HASH
#endif

/* The application's name, from CMake's APP_TITLE through build_id.h. The
 * fallback only matters to a build that bypasses CMake. */
#ifndef SHADOW_APP_NAME
#define SHADOW_APP_NAME "Halyard"
#endif

/* QT4 2026-10-03 - the rest of the identity, with the same fallbacks as the
 * name above. `build_id.h` carries the real values, generated from the ONE
 * declaration near the top of CMakeLists.txt; these exist so a translation
 * unit compiled without it still builds, and so an About box never shows an
 * empty line. */
#ifndef SHADOW_APP_AUTHOR
#define SHADOW_APP_AUTHOR "Wasabules"
#endif
#ifndef SHADOW_APP_URL
#define SHADOW_APP_URL "https://github.com/Wasabules/halyard"
#endif
#ifndef SHADOW_APP_LICENSE
#define SHADOW_APP_LICENSE "GPL-3.0-or-later"
#endif
#ifndef SHADOW_APP_DESC
#define SHADOW_APP_DESC "Unofficial Shadow PC client"
#endif

#endif /* SHADOW_VERSION_H */
